#!/bin/bash

# stop at the first error
set -eo pipefail

# vulnerability scanning - Nb. this scans non-staged files/dirs as well
#make scanrepo

# terraform scanning - Nb. this scans non-staged files/dirs as well
#make tfaudit
